### ISSUE TITLE
Implement commands

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#1]
`rvc list` lists out all configured VPNs
`rvc connect` connects all configured VPNs that are `preferred` (according to `rvc list`)
`rvc connect <VPN name>` where name is given in `rvc list`
`rvc kill --all` kills all VPN connections
`rvc kill <VPN name>` kills a single VPN connection in a similar fashion like #3
`rvc status` shows the status of all VPN connections (connected and not connected)
`rvc status <VPN name>` shows the status of a single VPN connection in a similar fashion like #3
`--json` gives out JSON output

**Comment by jjr840430** [comment]
@ronaldtse 
From my suggestion, I'm going to develop the following components:
- rvcd daemon
This daemon will be run as root privilege and managed by launchd.
It has the following functions:
> listening on commands by scripts
> managing openvpn connections by command
- rvc script
This script will be run as user privilege and work with the commands mentioned above.

**Comment by ronaldtse** [comment]
@jjr840430 this structure sounds good!

cc @erikbor

**Comment by erikbor** [comment]
Yup lets do it!

**Comment by erikbor** [comment]
@jjr840430 
Can you describe the 'rvcd' in detail please?
And in which language will you write 'rvcd'?

**Comment by jjr840430** [comment]
rvcd will run as launchd daemon on mac os and write in C language.

Will have the following modules:
1. Command processor module
This module will listen on Unix domain socket and get commands from shell script to manage VPN connections.
The commands may be composed by JSON format.

2. VPN connection management module
This module will up/down VPN connections and get the status of them.

**Comment by ronaldtse** [comment]
@jjr840430 @erikbor 

I have added a number of JSON command outputs ( #10 ), please see if they are appropriate and change/improve them if necessary. Thanks!
