### ISSUE TITLE
Create make target to upload new version release to GitHub

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#101]
Create new make target in the Makefile:

"make dist" to package a new version in tar.gz "rvc-${version}.tar.gz"

"make release" to upload above archive to github using the github-release tool.

**Comment by ronaldtse** [comment]
@jjr840430 would you have time to implement this? This would be useful not only here but also multiple other projects like [retrace](https://github.com/riboseinc/retrace/) 😉

**Comment by jjr840430** [comment]
@ronaldtse Thanks, I will implement it and update soon. :)

**Comment by jjr840430** [comment]
@ronaldtse May I close this issue?

**Comment by ronaldtse** [comment]
Yes, thanks!
