### ISSUE TITLE
Change `rvd` socket_path from `/tmp/.rvd_cmd` to `/var/run/rvd`

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#102]
Please change the `rvd` socket_path from `/tmp/.rvd_cmd` to `/var/run/rvd`. Other sockets are also residing in `/var/run`.

**Comment by ronaldtse** [comment]
Agree!

**Comment by erikbor** [comment]
@jjr840430 can you please hardcode this path (and take it out of `rvd.json`) instead of making this configurable in `/opt/rvc/etc/rvd.json`. This is because `rvc` cannot read `/opt/rvc/etc/rvd.json`.

**Comment by ronaldtse** [comment]
@erikbor what's the consideration to hard code the OpenVPN binary path in RVC? We should probably keep it configurable. RVC doesn't need to know the binary of OpenVPN, and if you want to expose that we could have an RVD socket command for that, which RVC could read?

**Comment by erikbor** [comment]
@ronaldtse `rvc` doesn't know the location of the `rvd` socket, so it cannot connect to it for the location of the `rvd` socket. Moving the socket out of `/tmp` will make `rvd` more like other daemons. Another solution than hardcoding the socket path would be to create a `rvc.json`?

**Comment by ronaldtse** [comment]
Oh I got confused, I thought you meant the OpenVPN binary path. Yes the /var/run patch could be hardcoded as a default, but we could also specify that in `rvd` startup options (e.g., `rvd -s /var/run/rvd`).

**Comment by jjr840430** [comment]
@ronaldtse If rvd should have the option related with socket path, then it needs to add an option into rvc too.
I think we may have hard-coded socket path for rvd and rvc both.

**Comment by erikbor** [comment]
@jjr840430 yeah exactly, I guess it's best to just remove the config option for `rvd` all together.

**Comment by ronaldtse** [comment]
Unless we separate RVD and RVC config since they run in root and user space respectively. We can go with hardcoding for now.

**Comment by jjr840430** [comment]
Fixed on #107
