### ISSUE TITLE
RVC configuration file location

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/rvc#11]
From README, then configuration file for RVC is located in ~/.setup/vpn/vpn.json.

@ronaldtse , What about placing it into /Application/rvc.app/Contents/Resources/config/ directory?

**Comment by ronaldtse** [comment]
We would want to place the configuration file in a user editable place, but the /Application path is not accessible.

**Comment by jjr840430** [comment]
But UI may write it into Applications/ directory.
Since rvcd is running as daemon mode with root privilege, it couldn't know the configuration path at startup.

**Comment by ronaldtse** [comment]
Hmm... We could hard code it into some path? We could technically have separate a "system-wide config" and "user-specific" configs.

**Comment by jjr840430** [comment]
Is it possible to specify configuration at run-time?
I'm not sure how UI loads and saves configuration.

**Comment by jjr840430** [comment]
@ronaldtse Can you check my opinion for configuration settings?

The management for configuration may be done by only core level.
The scenario is as the followings:

- Core will start the configuration with one in /Applications/rvc.app folder
- If user is going to add VPN connection, then it sends "add-connection" command to core.
- If user is going to remove VPN connection, then it sends 'remove-connect' command to core.

I think it would be work with UI and rvc utility without any problem.

**Comment by erikbor** [comment]
I suggest we hardcode the default configuration path to ```/usr/local/etc/rvcd.conf``` with the following permissions: ```-rwxr-----    1 root  wheel```. And make rvcd check for these permissions every time it starts.

**Comment by erikbor** [comment]
This issue is no longer relevant as we keep our config in `/opt/rvc/etc/rvd.json`
