### ISSUE TITLE
The script to build package

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/rvc#140]
@ronaldtse @erikbor Is it enough to just support homebrew?
How about adding the script to create the package for Mac?

**Comment by ronaldtse** [comment]
That would be easier to install because we can directly request the sudo password. How long do you think it takes?

**Comment by jjr840430** [comment]
It will be taken no much time. :)

**Comment by jjr840430** [comment]
@erikbor Do you think we need to put OpenVPN binary in the package file?

**Comment by erikbor** [comment]
@jjr840430 I'd rather not do that at this moment. There are too many supply chain risks that we would need to mitigate and we don't have the infrastructure for that (yet).

Maybe at a later stage?

**Comment by jjr840430** [comment]
@erikbor Agreed :)
