### ISSUE TITLE
Multiplatform supports

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/rvc#142]
Since rvc and rvd have been written by C, it's possible to port to other platforms such as Windows/CentOS/Ubuntu/FreeBSD systems.

**Comment by ronaldtse** [comment]
Agree! Can we first make it work on Linux and BSD with separate issues?

**Comment by jjr840430** [comment]
@ronaldtse Do we need `rvc` to work on Windows platform?

**Comment by ronaldtse** [comment]
@jjr840430 we don't need Windows right now. Thanks.
