### ISSUE TITLE
RVC should work on RHEL / CentOS

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#143]
We need to package RVC in `rpm` with a spec file and run via `systemd`.

Ref: #142

**Comment by jjr840430** [comment]
@ronaldtse OK, I will work on RHEL/CentOS.

**Comment by erikbor** [comment]
@jjr840430 btw you need to include a copy of strlcpy() and strlcat() from OpenBSD because RHEL glibc does not come with those (whereas *BSD and macOS do).

**Comment by erikbor** [comment]
The `PATH` in which RVC should be installed on non-macOS operating systems is `/usr/local/bin` and `openvpn_bin` in `rvd.json` should point to `/usr/sbin/openvpn`:

```console
$ ls -la /usr/sbin/openvpn
-rwxr-xr-x 1 root root 812464 Jun 21 18:23 /usr/sbin/openvpn
$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
```

**Comment by jjr840430** [comment]
@ronaldtse , @erikbor 

I modified `rvc` to work on RHEL and CentOS. Also, I added the script to build RPM on those platforms.
Please review, Thanks
