### ISSUE TITLE
'merge' status and list

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#149]
Hi @jjr840430 

We've been using RVC now a lot and we have not made any use of the `list` argument.
Can you please remove the `list` argument and add the output of `list` from: `auto-connect` and `pre-exec-cmd` to the `status` argument?

I will update the `README.md` to reflect the changes. Can you let Nikita know about the changes you will make so the GUI can also be updated?

Many thanks

**Comment by jjr840430** [comment]
@erikbor fixed.
