### ISSUE TITLE
the output of pre-connect-exec is no longer logged

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#151]
```console
$ sudo cat /opt/rvc/etc/vpn.d/test.json 
{
  "name": "test",
  "auto-connect": false,
  "pre-connect-exec": "date; exit 1"
}
```

```console
$ date
Fri Sep 29 10:31:06 HKT 2017
$ sudo grep HKT /var/log/rvd/test.ovpn.log 
$ 
```

I don't see the output of `date` in the log file. Can you please ensure that the output of the `pre-connect-exec` entries are logged into `/var/log/rvd/<VPN>.ovpn.log`?

We are having some problems with our MFA scripts and it was difficult to troubleshoot because the `pre-connect-exec` was basically a black hole.

Thanks!

**Comment by jjr840430** [comment]
@erikbor Fixed.
