### ISSUE TITLE
clean up macOS pkg building

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#168]
Hi @jjr840430, can you please clean up the macOS pkg building scripts?

There is now a lot of duplicate stuff going on in your scripts and the homebrew formula. I want to sync our efforts and prevent duplication. 

You now have included a `com.ribose.rvd.plist` which is fine but this was originally created by the homebrew formula. I will remove the `com.ribose.rvd.plist` creation from the homebrew formula and use yours in `platforms/osx` (soon: `platforms/macos`).

## use the homebrew formula installation notes code for `postinstall` 
The `platforms/osx/scripts/postinstall` has a lot of redundancy with the installation notes of the homebrew formula. Can you please use the code from homebrew formula? Once you have done that I will remove the installation steps described in the formula and point to your `postinstall` script. Btw: It's easier to use `install` instead of doing `cp` and `chown`. It's available on macOS and RHEL/CentOS.

## use of `/tmp`
Is it possible to have `osx/scripts/postinstall` and `osx/scripts/preinstall` use `/tmp` instead of `/opt/rvc.dist` for `RVC_DATA_DIR`? This is to not touch `/opt` in any way for these operations as it's not meant for that (unless it's technically not possible otherwise). Do we really need `RVC_DATA_DIR`?

## remove compilation steps from `build_macos_pkg.sh`
Can you please remove the `./autogen.sh`, `./configure`, `make` steps from `build_macos_pkg.sh` and execute `build_macos.sh` instead? This removes duplication.

## set `OPENVPN_BINARY_PATH` to `/opt/openvpn/sbin/openvpn`
```console
$ grep -n OPENVPN_BINARY_PATH configure.ac
76:    OPENVPN_BINARY_PATH=/opt/rvc/sbin/openvpn
```
The homebrew formula states that `openvpn` needs to be installed in `/opt/openvpn/sbin/openvpn`

## typo `binrary` -> `binary`
```console
$ grep -rn binrary *
README.md:226:	/* get stat of openvpn binrary file */
autom4te.cache/traces.2:660:m4trace:configure.ac:91: -1- AH_OUTPUT([OPENVPN_BINARY_PATH], [/* The path to OpenVPN binrary */
config.h:58:/* The path to OpenVPN binrary */
config.h.in:57:/* The path to OpenVPN binrary */
configure.ac:91:AC_DEFINE_UNQUOTED([OPENVPN_BINARY_PATH], ["$OPENVPN_BINARY_PATH"], [The path to OpenVPN binrary])
src/vpn.c:340: * check whether openvpn binrary is available
src/vpn.c:347:	/* get stat of openvpn binrary file */
src/vpn.c:623:	/* check openvpn binrary */
src/vpn.c:625:		RVD_DEBUG_ERR("VPN: Failed to check openvpn binrary availability.");
```

**Comment by ronaldtse** [comment]
@jjr840430 please also update the `homebrew` formula to use the new `.plist` file. The `.plist` file should be installed by Homebrew on macOS.

**Comment by jjr840430** [comment]
@erikbor Fixed issues.
