### ISSUE TITLE
Please put back `/opt/rvc/sbin/rvd` to `/opt/rvc/bin/rvd`

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#176]
We initially did not use `/opt/rvc/sbin/rvd`, I'm not sure when this got introduced but it was one of the reasons why the homebrew formula broke last week.

`/sbin` is used for statically compiled executables while `/bin` holds dynamically linked executables. On macOS every executable is dynamically linked so there is no need/benefit to create a `/opt/rvc/sbin` for `rvd` while `rvc` lives in `/opt/rvc/bin`. It's cleaner to follow that practice and keep RVC executables in one place.

Thanks!

**Comment by jjr840430** [comment]
fixed by #181
