### ISSUE TITLE
Copy `platforms/macos/scripts/postinstall` to `/usr/local/bin` with `make install`

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#177]
When we have the `postinstall` script in `/usr/local/bin` then it will be easier for the homebrew formula to set permissions and install everything in `/opt`

**Comment by jjr840430** [comment]
@erikbor After running `make install`, `rvc_install.sh` will be copied to `/usr/local/bin`.

So homebrew may install `rvc` to `/opt` directory using the following command.

```
sudo /usr/local/bin/rvc_install.sh
```

**Comment by jjr840430** [comment]
fixed by #181
