### ISSUE TITLE
rvcd does not pick up changes in .setup/vpn/vpn.json

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#18]
```sh
$ cat /Users/test/.setup/vpn/vpn.json
[
  {
    "name": "stagingfoobar.baz",
    "ovpn": "/Users/test/test.ovpn",
    "autoconnect": "true",
    "up-script": "",
    "down-script": ""
  }
]
$ sudo ./src/rvcd -c /Users/test/.setup/vpn/vpn.json
Fri 18 Aug 2017 12:19:01        INFO : Main: Initializing rvcd context(at rvcd.c:163)
Fri 18 Aug 2017 12:19:01        INFO : CMD: Initializing rvcd command processor(at cmd.c:496)
Fri 18 Aug 2017 12:19:01        INFO : VPN: Initializing VPN connection manager(at vpn.c:1148)
Fri 18 Aug 2017 12:19:01        INFO : CMD: Starting rvcd command processing thread(at cmd.c:400)
Fri 18 Aug 2017 12:19:01        INFO : VPN: Reading configuration from '/Users/test/.setup/vpn/vpn.json'(at vpn.c:884)
Fri 18 Aug 2017 12:19:01        INFO : VPN: Added VPN configuration with name 'stagingfoobar.baz', openvpn path '/Users/test/test.ovpn'(at vpn.c:86)
Fri 18 Aug 2017 12:19:01        INFO : VPN: Starting VPN connection monitoring thread with name 'stagingfoobar.baz'(at vpn.c:1059)
```

In another terminal:
```
$ ./rvc -l
name: stagingfoobar.baz
		profile: /Users/test/test.ovpn
		auto-connect: Disabled
		up-script: none
		down-script:none
```

In that terminal I add another connection in ```/Users/test/.setup/vpn/vpn.json```:
```sh
$ cat /Users/test/.setup/vpn/vpn.json
[
  {
    "name": "stagingfoobar.baz",
    "ovpn": "/Users/test/test.ovpn",
    "autoconnect": "true",
    "up-script": "",
    "down-script": ""
  },
  {
    "name": "staging2foobar.baz",
    "ovpn": "/Users/test/test2.ovpn",
    "autoconnect": "false",
    "up-script": "",
    "down-script": ""
  }
]
```
I saved it but rvcd does not pick up the changes

**Comment by jjr840430** [comment]
@erikbor 
I think that it needs to add/remove VPN connections using rvc utility without modifying the configuration file directly.
i.e. We may add the following options into rvc utility.

rvc -a {JSON connection info}
rvc -r <connection name>

What do you think about that thoughts?

**Comment by ronaldtse** [comment]
@jjr840430 that's actually a good idea, but maybe we should also allow reloading of config file:

```sh
rvc add-connection {JSON connection info}
rvc remove-connection 'my-connection'
rvc reload-config
```

**Comment by jjr840430** [comment]
@ronaldtse Can you clarify when removing or reloading the active connections?

so, assume the connection 'mytest1' was connected and try to remove it using rvc utility.
At this case, I think rvc utility should show error message and removing would be failed.
i.e. removing connection may be succeeded after disconnected the connection.

**Comment by erikbor** [comment]
I think from a security perspective we don't want the rvc utility to add or remove any VPN configurations. The reason is that malicious payload could be inserted in the start/stop scripts and having rvcd just blindly executing this is not wanted behaviour. If you want to add a new configuration then users are required to use sudo.

**Comment by ronaldtse** [comment]
@erikbor if that's the case then we need to enforce rvcd to only allow running with config files of root permission, enforcing a behavior kind of like ssh keys?

**Comment by erikbor** [comment]
@ronaldtse yeah I mentioned that in [11](https://github.com/riboseinc/rvc/issues/11)

**Comment by ronaldtse** [comment]
Looks good @erikbor! Let's do that then.

**Comment by jjr840430** [comment]
@erikbor If UI is going to add or delete a connection, then how it would tell to rvcd to do that?

**Comment by erikbor** [comment]
@jjr840430 The UI should not be able to add or delete connections, only start/stop existing ones.

**Comment by jjr840430** [comment]
@erikbor What's your thoughts for reloading the configuration?
Anyway, something should notice to rvcd that the configuration has modified.

**Comment by erikbor** [comment]
I think rvcd should monitor the config file in a inotify() way (like on Linux)

**Comment by jjr840430** [comment]
How about sending a notification using rvc utility after modified the configuration?
Something like as: rvc reload-config

**Comment by ronaldtse** [comment]
Apparently there is no `inotify` on macOS, a list of alternatives on [SO](https://stackoverflow.com/questions/1515730/is-there-a-command-like-watch-or-inotifywait-on-the-mac)

**Comment by jjr840430** [comment]
I think that it's not efficient way to monitor the configuration file.
Anyone may save the non-completed configuration sometimes while editing the configuration file, so reloading may be failed.
So it needs to notice to rvcd that the configuration has completely modified.

**Comment by ronaldtse** [comment]
Yes @jjr840430 it is true that there will be failures. It's much easier if there is a command to reload config. @erikbor 's concern is that non-privileged users may be able to trigger a reload, so if we prevent that it would be OK.

**Comment by jjr840430** [comment]
@ronaldtse @erikbor 

We may introduce PrivilegedHelper launching on MacOS.
i.e. The installation and reloading of rvcd daemon may be done by UI using PrivilegedHelper technology on MacOS.

To do it, UI and rvcd daemon should be signed by Apple Developer ID certificate.
Only signed applications may control the rvcd daemon.

Here is the link to implement PrivilegedHelper.
https://developer.apple.com/library/content/documentation/Security/Conceptual/SecureCodingGuide/Articles/AccessControl.html

**Comment by jjr840430** [comment]
Here is the sample code between UI and helper daemon using SMJobBless and XPC communication.
https://github.com/atnan/SMJobBlessXPC

**Comment by erikbor** [comment]
@jjr840430 @ronaldtse having a PrivilegedHelper really overcomplicates things.

Make a sha1 sum of the config file in memory and diff it, if there's a change then load the config. I think we are over worrying about configs failing or not loading. We don't destroy the in-memory config so if a new/modified VPN does not load we spit out an error and ignore that VPN. The same would happen anyway when you'd load it and "restart" rvcd using ```rvc reload```

**Comment by ronaldtse** [comment]
In any case, we already need to sign the UI. The thing is if we need to "watch changes" on macOS then we already need a third-party utility to do so. 

I'm just wondering the difference between:
1. Using a command `rvc reload`
2. Detecting changes in the config file

The first is so much easier to do compared to the second one. What's the major benefit of the second?

**Comment by erikbor** [comment]
We don't need third-party modules, even monitoring using stat() mtime would work.

My major objections are that we're introducing a dependency on the UI for reloading while the original design was fully CLI-driven. This leaves CLI users (future Linux, BSD?) without an option to reload.

Regarding the differences:
The first one is not easier to implement because there is no way to securely make rvcd reload its config from a non-privileged user. Making rvcd check the config every 3 seconds is a for (;;) check_config_changes() == 0 { reload() }.

Another approach could be this:
rvcd will be managed by launchd so we could do **sudo** launchctl rvcd reload
One needs **sudo** vi config.json anyway...

**Comment by ronaldtse** [comment]
On a mac I assumed rvcd needs to use launchd since that's the only way it could launch using root?

I agree that we should stick with portability.  My concern with the auto-reload is transparency since it is happening without user intervention.

Another method is for `rvcd` to create a local socket that only root can write to -- then only root can issue the `reload` command to it?

**Comment by erikbor** [comment]
Yeah I actually meant that we can use ```sudo launchctl rvcd reload``` to reload the configuration like a lot of daemons on Linux that you can ```kill -HUP``` to reload. I assume signals on macOS have identical/similar behaviour.

The root socket could also work, and then performing a ```getuid() == 0``` check in ```rvc``` upon ```reload```. In the reload case ```rvc``` needs to be executed by ```sudo```.

**Comment by jjr840430** [comment]
@ronaldtse @erikbor 
I think that restarting rvcd by launchctl would be the solution to reload configuration.

**Comment by erikbor** [comment]
@jjr840430 okay cool, lets do it that way if @ronaldtse agrees

**Comment by ronaldtse** [comment]
Agree. When you guys were posting I was actually looking for an example.

In certain brew formulas, there is an extra "caveats" step that informs the user of what else needs to be done after install. We can indicate to the user that an `sudo` step is necessary to edit the config file and make `launchctl` start `rvcd`.

e.g., 
https://github.com/Homebrew/homebrew-core/blob/master/Formula/nginx.rb

**Comment by jjr840430** [comment]
This issue is duplicated with #93
