### ISSUE TITLE
Add tests for Travis CI

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#209]
@jjr840430 could you help add some tests for Travis?

The pre-auth script currently is running under `root` and failing some pre-auth scripts that depend on the user that is connecting.

The tests should setup an OpenVPN server locally and try to use rvc to connect to it.

**Comment by jjr840430** [comment]
@ronaldtse OK, I will try to integrate `rvc` with `travis ci`

**Comment by ronaldtse** [comment]
## Prerequisites

1. Setup OpenVPN server with local certificate (run in Travis `sudo` mode)
2. Allow OpenVPN client to connect to itself 

## Test OpenVPN binary permissions

1. If binary has right permissions, can connect.
2. If binary has wrong permissions, check error message is correct.

## Test RVD config (`rvd.json`) permissions

1. If config permission is right, RVD can start.
2. Otherwise, gives out correct error.

## Test RVC per-connection files (`.ovpn` / `.json`)

1. If connection config permission is right, can connect.
2. Otherwise, gives out correct error.
3. If missing config (`[connection].json` file not present), should still work, and display in `rvc status` that the config file is missing and is using default (show the config being used).
4. If missing `ovpn` file, should display in `rvc status` that has config but no `ovpn` file, and therefore cannot connect.
5. If broken config, should show message in `rvc status`, and other connections still work.
6. If multiple locations of connection files, and two have the same name, how to resolve (display both in rvc status, and give them different names).

## Test pre-exec

1. Pre-exec empty (NULL or empty string), can connect.
2. Pre-exec return non-0, cannot connect.
3. Pre-exec return 0, can connect.
4. Connect and then change pre-connect to fail, connection stays active, re-connect, cannot connect.
5. Test pre-exec is run using user specified in `rvd.json` with the correct UID.

## Test reload

1. Connect, reload, can still connect automatically
2. Connect, add configuration, reload, can connect new connection
3. Connect, remove configuration, reload, can no longer find connection

## Simulate dead OpenVPN client

1. Connect, then kill OpenVPN client, RVD should find out and re-start it.

## Ensure OpenVPN client killed

1. Connect, disconnect. Ensure OpenVPN client process is gone.

## Test Auto-Connect

1. Set connection auto-connect to true. Start RVC, it should automatically connect.
2. Set connection auto-connect to false. Start RVC, it should not connect.

## Test writing to log

1. If cannot write to log files (permissions), fail with correct message.

## Test can open socket

1. If cannot open `/var/run/rvd`, fail with correct message.

## Can read from OpenVPN socket

**Comment by jjr840430** [comment]
@ronaldtse Thanks for your advice.

**Comment by jjr840430** [comment]
@ronaldtse The testing cases were implemented in #217 . Please review it and let me know your opinions.
Thanks. Jin.

**Comment by ronaldtse** [comment]
Confirmed.
