### ISSUE TITLE
Enhance `rvd` its checking of `DISCONNECTING` and `CONNECTING` mode

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#214]
Hi @jjr840430 

Sometimes we have the situation that `rvc` shows some VPNs that are stuck in `DISCONNECTING` and `CONNECTING` mode. Can you implement some checking in `rvd` that when a VPN gets into `DISCONNECTING` and `CONNECTING` mode this can't keep in that state forever? E.g. if a VPN cannot connect within 10 seconds (or any other value) then it should go into `DISCONNECTED` mode. Same for `DISCONNECTING`.

I know that the current behaviour of `rvd` already more or less does this but we'd like to have some extra checks to prevent the edge cases (e.g. `openvpn` hangs, died etc). 

Thanks!!!

**Comment by jjr840430** [comment]
@erikbor Currently `rvd` has that function.
Can you upload log files for this case?

**Comment by ronaldtse** [comment]
@jjr840430 I confirm that I'm seeing this issue too.

**Comment by jjr840430** [comment]
@ronaldtse Can you upload the log file here?
I just got the issue on my side too. It's from bug related to `pre-exec-cmd`.
I want to check whether your side has the similar issue.

**Comment by erikbor** [comment]
@jjr840430 I'm sorry we don't have any log files. The behaviour is to unpredictable that we cannot provide a repeatable example + log file.

**Comment by jjr840430** [comment]
@erikbor It seems fixed by #215

**Comment by ronaldtse** [comment]
Looks like it. Thanks!
