### ISSUE TITLE
Do not need "name" attribute in per-connection JSON config

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#218]
Today the JSON config per connection is like:

```json
{
  "name": 1234,
  "auto-connect": true,
  "pre-auth": "/bin/abc"
}
```

But the "name" isn't necessary since the filename (`xyz.json`) already contains the name (`xyz`). Currently RVD fails to run when the configuration file fails, like this:

```
2017-12-08T12:19:19HKT	INFO : CONF: Parsing configuration file '/opt/rvc/etc/vpn.d/12345.json'(at conf.c:168)
```

@jjr840430 Let's get rid of the "name" attribute and use the name from the filename.

Thanks!

**Comment by jjr840430** [comment]
@ronaldtse Agreed. I will modify soon.

**Comment by ronaldtse** [comment]
Thanks @jjr840430

**Comment by ronaldtse** [comment]
@jjr840430 is this now fixed? Thanks.

**Comment by jjr840430** [comment]
@ronaldtse It was fixed. Thanks.
