### ISSUE TITLE
Add Coverity scan

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#229]
https://scan.coverity.com/projects/riboseinc-rvc?tab=overview

@jjr840430  could you help:

1. Add Coverity Scan to RVC just like retrace?
2. Add Coverity Scan badge to README

Thanks!

**Comment by jjr840430** [comment]
@ronaldtse When I'm going to access `Project settings` or `Project Overview` on `dashboard` of the Coverity scan, it said `You are not authorized to access this page`.
Can you please check it?

**Comment by ronaldtse** [comment]
@jjr840430 I've added you as a maintainer. Does it work now?

**Comment by jjr840430** [comment]
@ronaldtse It seems working! Thanks. 👍

**Comment by ronaldtse** [comment]
👍

**Comment by jjr840430** [comment]
@ronaldtse Can you register me for the Coverity scan of `retrace`?

**Comment by ronaldtse** [comment]
Done!

**Comment by jjr840430** [comment]
@ronaldtse Can you please review #230 ? Thanks.

**Comment by ronaldtse** [comment]
Done in #230.
