### ISSUE TITLE
Modify the json output of `rvc status`

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#236]
Hi @jjr840430,

Can you please modify/rearrange the output of `rvc all status --json` to the following structure:

```
RvdConnections [
  RvdConnection {
    name,
    profile,
    autoConnect,
    assignedIp,
    endpoint,
    protocol,
    ipVersion,
    port,
    RvdConnectionStatus {
      state
      ovpnState
      connectionTime
      connectedBy
      netIn
      netOut
    },
    RvdPreExec {
      command
      interval
      userId
      output
      returnCode
    }
  }
]
```

We want to make it easier to interpret the output of RVC for 3rd party logging/management tooling so the output of RVC needs to be a little bit more structured hence this request.

Thanks!

**Comment by jjr840430** [comment]
@erikbor OK, I will modify as you described.

**Comment by erikbor** [comment]
@jjr840430 please see attached diagram:
![_processevent](https://user-images.githubusercontent.com/25045442/35135141-164d7fca-fd16-11e7-99b2-dcfb76857ea1.png)

**Comment by jjr840430** [comment]
ok, thanks, I will update `rvc` to implement it.

**Comment by jjr840430** [comment]
@erikbor Can you check the following `JSON` example?

RvdConnections: [
	{
		"name": "vpn1",
		"profile": "/opt/rvc/etc/vpn.d/vpn1.ovpn",
		"autoConnect": 1,

		"assignedIp": {
			"address": "10.10.10.1",
			"netmask": 32
		},

		"endpointIp": {
			"address": "172.16.0.101",
			"netmask": 16
		},

		"protocol": "udp",
		"ipVersion": 4,
		"port": 1194,

		"RvdConnectionStatus": {
			"state": "CONNECTING",
			"ovpnState": "ASSIGN_IP",
			"connectionTime": "2018-01-15T15:53:00",
			"connectedBy": "?",
			"netIn": 5423,
			"netOut": 3468
		},

		"RvdPreExec": {
			"command": "/bin/ls",
			"interval": 15,
			"userId": 501,
			"output": "bin etc",
			"returnCode": 0
		}
	}
]

Also, can you explain about `connectedByte` filed?

**Comment by jjr840430** [comment]
@erikbor Can you clarify what's mean `endpoint` and `endpointIp` fields?

**Comment by erikbor** [comment]
@jjr840430 The `endpoint` is the VPN server that is configured in the .json, and the `endpointIp` should be the actual IP `rvd` is connected to.

This for logging purposes so we can track to which IP the client was connected at a particular time.

**Comment by jjr840430** [comment]
Do we need to specify `netmask`?
When specifying the address of openvpn server, `netmask` isn't involved.
Also, `assignedIp` field is valid only when VPN connection was established.

**Comment by erikbor** [comment]
`netmask` can be `/32` for IPv4 and `/128` for IPv6

Yeah correct about the `assignedIp`, same goes for `endpointIp` etc.

**Comment by jjr840430** [comment]
May I have your Skype?

**Comment by jjr840430** [comment]
@erikbor Can you please review #237 ?

**Comment by ronaldtse** [comment]
For the record, the event model is located at https://github.com/riboseinc/event-configuration-models with the specific RVC/RVD one at https://github.com/riboseinc/event-configuration-models#example-rvcrvd
