### ISSUE TITLE
Replace configuration functions (configuration file, command line arguments) with libnereon

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#239]
Related to https://github.com/riboseinc/kaohi/issues/14

This issue is to extract out all configuration related code into a new library, according to https://github.com/riboseinc/event-configuration-models .

This will allow RVC/RVD to take advantage of the ConfigScheme model, autogenerate help output, parse command line options, environment variables, and config files.

**Comment by jjr840430** [comment]
@ronaldtse, @erikbor 

Here are the RVD/RVC configurations for `libnereon`:

- [rvd.mel](https://github.com/riboseinc/rvc/blob/v1.2.0/etc/rvd.mel)
- [rvd.conf](https://github.com/riboseinc/rvc/blob/v1.2.0/etc/rvd.conf)
- [rvc.mel](https://github.com/riboseinc/rvc/blob/v1.2.0/etc/rvc.mel)

Can you please review them and let me know your thoughts about them?

**Comment by erikbor** [comment]
Hi @jjr840430,

Looks good. Can you change the following please:

s/globals/global
s/goes daemon/daemonize
s/"Override DNS settings.(sudo required)""/"Override DNS settings (sudo required)"
s/Print Help message/Print help message
s/Restrict the access to communication socket/Restrict access to communication socket

Cheers

**Comment by jjr840430** [comment]
@erikbor Thanks for your advise, I fixed and updated.

**Comment by ronaldtse** [comment]
The idea behind the new file extensions are shown here: https://github.com/riboseinc/nereon

**Comment by ronaldtse** [comment]
@jjr840430 we will also need to allow setting configuration of the existing configuration -- maybe we need a conversion script to convert JSON into NOC? What do you think?

**Comment by jjr840430** [comment]
@ronaldtse That's a great idea. I will create the script to convert JSON into NOC.

**Comment by jjr840430** [comment]
@ronaldtse Fixed by #241
