### ISSUE TITLE
Update documentation for Nereon config files, no longer JSON

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#242]
The latest RVC 1.2.0 uses Nereon rather than JSON configuration. We need to update all the instances in the README.

**Comment by ronaldtse** [comment]
@jjr840430 could you help update the README? How does one configure say `/opt/rvc/vpn.d/my-vpn-connection.conf` ?

**Comment by jjr840430** [comment]
fixed by #250
