### ISSUE TITLE
Update RVC to change `config-status: JSON configuration exists`

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#248]
We don't use JSON config but now use NOC config syntax.

**Comment by erikbor** [comment]
Hi @jjr840430,

Can you also update the `README` to remove all instances of json. Thanks!

**Comment by jjr840430** [comment]
@erikbor I will remove all JSON instances on next pull request. Thanks!

**Comment by jjr840430** [comment]
@erikbor Fixed by #250
