### ISSUE TITLE
`rvc status` should equal to `rvc status all`

### ISSUE THREAD

**Issue by PeterTKY** [riboseinc/rvc#253]
Right now:

> $rvc status
Failed to parse command line(err:Missing argument for switch 'status')
Usage: rvc [options]
    connect         <all|connection name>                                        : connect to a VPN with given name (default:all)
    disconnect      <all|connection name>                                        : disconnect VPN with given name (default:all)
    reconnect       <all|connection name>                                        : reconnect VPN with given name (default:all)
    status          <all|connection name>                                        : get status of VPN connection with given name (default:all)
    json                                                                         : display output as JSON format
    edit            <connection name> <auto-connect|pre-exec-cmd|profile> <value>: edit VPN connection with given name
    remove          <connection name> [force]                                    : remove VPN connection (sudo required)
    import          <new-from-tblk|new-from-ovpn> <path>                         : import VPN connection (sudo required)
    reload                                                                       : reload configuration (sudo required)
    dns-override    <enable <DNS serve IP list>|disable|status>                  : override DNS settings (sudo required)
    script-security <enable|disable>                                             : enable/disable script security
    version                                                                      : print version
    help                                                                         : print help message

In Usage, it says the default argument of `rvc status` should be 'all'. But right now it shows an error of "Missing argument for switch 'status'".

Please fix. Thanks!

**Comment by jjr840430** [comment]
@PeterTKY, I removed `default:all` from NOS options. Please check [here]<https://github.com/riboseinc/rvc/pull/254>

**Comment by ronaldtse** [comment]
@jjr840430 is it possible to add back `default:all`? Thanks.

**Comment by jjr840430** [comment]
@ronaldtse Here is the example of how to apply subcommand:

```
config_option "edit" {
	type = "string"

	cmdline "switch" {
		long = "edit"
	}

	cmdline arguments {
		auto-connect {
			type = string
		}

		pre-exec-cmd {
			type = string
		}

		profile {
			type = string
		}
		mandatory = true
	}

	cmdline "description" {
		short = "<connection name> <auto-connect|pre-exec-cmd|profile> <value>"
		long = "edit VPN connection with given name"
	}
}
```

`edit` command line switch has the arguments such as `auto-connect`, `pre-exec-cmd`, 'profile', and those arguments also may have sub-arguments.
Now `libnereon` implemented that function.
