### ISSUE TITLE
implementation request: disable 'up-script' and 'down-script' options by default

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#27]
@jjr840430 can you please implement a cmd line switch for rvcd that enables the 'up-script' and 'down-script' options and disable (ignores) these options by default?

I'd like to prevent any local compromises by malicious .ovpn/.json files and put the responsibility to the user to enable these options him/herself.

Thanks

**Comment by jjr840430** [comment]
Implemented on #53
