### ISSUE TITLE
rvc: change the argument switches to names

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#38]
Please change the rvc switches to names:
```-l``` -> ```list```
```-c``` -> ```connect```
```-d``` -> ```disconnect```
```-s``` -> ```status```

I think ```-j``` can stay as it is

**Comment by ronaldtse** [comment]
Yes this is much clearer. `-j / --json` is separate because you can use `rvc list --json` 👍

**Comment by jjr840430** [comment]
Fixed on #39
