### ISSUE TITLE
create a homebrew formula

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#48]
Hi @jjr840430 can you please create a homebrew formula for rvc?

It should depend on openvpn, please see [homebrew-rvc](https://github.com/riboseinc/homebrew-rvc/issues)

Thanks!

**Comment by jjr840430** [comment]
@erikbor I will create that. Thanks.

**Comment by erikbor** [comment]
@jjr840430 how's it going? need any help?

**Comment by jjr840430** [comment]
@erikbor Will work on this from today.

**Comment by ronaldtse** [comment]
@jjr840430 do you have a mac?

**Comment by jjr840430** [comment]
Yes, I have Mac.

**Comment by ronaldtse** [comment]
👍
