### ISSUE TITLE
Ensure macOS maintenance scripts take care of RVC/RVD log files

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#81]
We don't want /var/log/rvd.log getting huge, default macOS cleanups should help clean it up too.

**Comment by jjr840430** [comment]
@ronaldtse The default maximum size of the log file is 30Mbytes.
If maximum size was detected, then rvd will backup log file and create a new one.

**Comment by ronaldtse** [comment]
Thanks @jjr840430 !
