### ISSUE TITLE
Modify rvd vpn behaviour

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#82]
@jjr840430 we've been working with ```rvc``` and ```rvd``` and have some requests to make life a little bit more easier.

Can you implement the loading of a .ovpn file without a corresponding .json file.
The default settings would be: VPN name is filename of the .ovpn file, auto-connect set to false and no pre-exec script.

With this we have to create .json files only for VPNs that require auto-connect and pre-exec.
So we copy a .ovpn file to ```/opt/rvc/etc/vpn.d```, restart ```rvd``` and can connect/disconnect with ```rvc```

**Comment by jjr840430** [comment]
@erikbor That's clear requirements. I will implement soon.

**Comment by ronaldtse** [comment]
@erikbor @jjr840430 or maybe we don't even need to restart `rvd` if we use something like `fswatch`?

https://stackoverflow.com/questions/1515730/is-there-a-command-like-watch-or-inotifywait-on-the-mac

Given we are using Homebrew anyway, we can also require `fswatch`.

**Comment by erikbor** [comment]
@ronaldtse how would ```fswatch``` be used?

**Comment by ronaldtse** [comment]
@erikbor watch the directory and see if any new files or files changed, and call something like `rvc update` to update?

**Comment by jjr840430** [comment]
@ronaldtse If there is any pending edition of the config file, then reloading rvd will be failed.
So it needs to confirm that the config has been modified.

I think we need to add this confirmation into rvc utility.
If it has some security issues, then we may introduce username/password authentication for some behaviors.

Something like as https://www.ribose.com/#spaces/fa32f310-e994-4571-9e61-c5a9d0382032/conversation/conversations/9bd102fa-e267-43e0-8e32-bec5c903c6ab

**Comment by erikbor** [comment]
@ronaldtse  ```rvc``` could indeed be used to initiate a rescan of ```/opt/rvc/etc/vpn.d```, I like that! @jjr840430 I don't see security risks with that approach. One will still need root privileges to write in ```vpn.d``` and files writable by others will be ignored.

---

I don't like having a tool (```fswatch```) run all the time because we already have ```rvd``` running which could do exactly the same thing. Implementation in ```rvd``` makes so much sense. We could disable the rescan behaviour by default in ```rvd.json``` and let users enable it whenever they want to. Any users that want to use ```fswatch``` can use that instead if they feel having that running is better?

**Comment by ronaldtse** [comment]
But if there is any broken `*.json` file, `rvd` should just ignore that, right?

**Comment by erikbor** [comment]
@ronaldtse yeah I think that would be the best behaviour, ignore it, log it and show it as ``broken``` in ```rvc list```.

**Comment by erikbor** [comment]
And that should also apply to any broken ```.ovpn``` file

**Comment by jjr840430** [comment]
Fixed on #87
