### ISSUE TITLE
Change owner of VPN connection logs from root to the UID defined in rvd.json

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#83]
@jjr840430 can you please change the owner of VPN connection logs from the root user to the ```user_id``` as defined in ```rvd.json```?
That way we can just ``rm /tmp/logfile``` without having to use sudo.

Current situation:
```sh
$ ls -la /tmp/ct.ovpn.log 
-rw-------  1 root  wheel  1000 Sep  6 11:58 /tmp/ct.ovpn.log
```

Desired situation (user_id from rvd.json):
```
-rw-------  1 test  staff  1000 Sep  6 11:58 /tmp/ct.ovpn.log
```

**Comment by jjr840430** [comment]
fixed on #97
