### ISSUE TITLE
rvc config in /opt/rvc/etc/vpn.d/xxx.json should work regardless of permissions?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#89]
```console
user@[/opt/rvc/etc/vpn.d]: ls -al
total 48
drwxr-xr-x  6 root  wheel   204 Sep  6 18:02 .
drwxr-xr-x  4 root  wheel   136 Sep  6 13:52 ..
-rw-------  1 root  wheel    70 Sep  6 11:59 conn1.json
-rw-------  1 root  wheel  4297 Sep  6 12:07 conn1.ovpn
-rw-r--r--  1 root  wheel    83 Sep  6 18:02 conn2.json
-rw-r--r--  1 root  wheel  4373 Sep  6 18:01 conn2.ovpn
```

After restart, `conn2` is still not shown in `rvc status`. I had to do `chmod 600 conn2.*`, restart rvc, for it to work.

I think those files could have any permissions?

Or, rvc should at least show in logs or in `rvc status` that `conn2` has the wrong permissions and how to fix it?

**Comment by erikbor** [comment]
@ronaldtse the permission check is needed so we don't leak our private keys in exposed `.ovpn` files (similar how OpenSSH checks private keys)

And yeah `rvd` should log that wrong permissions are set, and `rvc` should show this too.

**Comment by ronaldtse** [comment]
Got it. Thanks @erikbor !

**Comment by jjr840430** [comment]
@ronaldtse @erikbor rvd is currently logging the error message when .ovpn has invalid permission.

**Comment by ronaldtse** [comment]
@erikbor can close?
