### ISSUE TITLE
Utilize OpenVPN management interface

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#9]
OpenVPN supports a management interface that can be used with TCP / telnet.

See https://community.openvpn.net/openvpn/wiki/HOWTO#Usingthemanagementinterface

And https://github.com/OpenVPN/openvpn/blob/master/doc/management-notes.txt

We could use this to implement status showing and connection toggling.

**Comment by jjr840430** [comment]
@ronaldtse It was already implemented on rvcd side. :)

**Comment by ronaldtse** [comment]
Nice 👍
