### ISSUE TITLE
`rvc status` should show some table instead of plain JSON

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#90]
For better readability.

**Comment by ronaldtse** [comment]
And `rvc status all --json` fails with a help message.

**Comment by erikbor** [comment]
Reference: [88](https://github.com/riboseinc/rvc/issues/88)

**Comment by ronaldtse** [comment]
Thanks @erikbor !

**Comment by jjr840430** [comment]
fixed on #98
