### ISSUE TITLE
Enforce that VPN names in .json files should begin and end with an alpha numeric character [a-z|A-Z][0-9]

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#92]
This is to prevent confusion in case a user creates a VPN with a name such as `--json`

**Comment by jjr840430** [comment]
@erikbor Currently, rvd checks whether the first character of VPN connection name is alphabetic or digit.
Is it need to check that for the last character too?

**Comment by erikbor** [comment]
@jjr840430 hmm I see, yeah could you please add the last character check too? Thanks!

**Comment by jjr840430** [comment]
fixed on #100
