### ISSUE TITLE
Implement a reload configuration option in `rvc` and `rvd`

### ISSUE THREAD

**Issue by erikbor** [riboseinc/rvc#93]
@jjr840430 could you implement a reload configuration option in `rvc` and `rvd` please.

`rvc` connects to the socket and tells `rvd` to rescan `/opt/rvc/etc/vpn.d` and add/remove any VPNs that are added/removed.

So if we were to add a new `.ovpn` file in `/opt/rvc/etc/vpn.d` then we can run `rvc reload` and make the new VPN visible with `rvc list`.

**Comment by jjr840430** [comment]
To reload rvd process, rvc should run as sudo privilege and reload the rvd process directly.
So it needs to know whether rvd daemon was installed as launch daemon before reloading it.

@erikbor @ronaldtse What's your thoughts on that?

**Comment by erikbor** [comment]
@jjr840430 what would `rvc` do to reload `rvd`? Kill it?

**Comment by ronaldtse** [comment]
RVD reload should not be an actual "reload" of the process, but just a "reload" of all configuration. RVC should only tell RVD to reload the VPN config, not kill and restart the process. Kill and restart is only done via launchctl.

**Comment by jjr840430** [comment]
@ronaldtse That makes sense. I will implement it by sending a specific signal to rvd process.

**Comment by ronaldtse** [comment]
Thank you @jjr840430 !

**Comment by jjr840430** [comment]
Implemented on #106
